const randomEmailGenerator = require("./randomEmailGenerator");
const autoGeneratedPassword = require("./autoGeneratedPasswords");
const randomPostcodeGenerator = require("./randomPostcodeGenerator.js");
const randomMobileNumber = require("./randomGeneratedMobileNr");

module.exports = {
  createAccount() {
    this.clickSignIn();
    const createEmailAddress = this.enterEmailAddress();
    this.createAccountBtn();
    this.titleSelection();
    this.enterFirstName();
    this.enterLastName();
    this.validateEmailField(createEmailAddress);
    const pswLogIn = this.randomPassowrd();
    this.dateOfBirthDay();
    this.dateOfBirthMonth();
    this.dateOfBirthYear();
    this.addressEntry();
    this.cityEntry();
    this.selectState();
    this.enterPostcode();
    this.enterMobile();
    this.submitRegistrationForm();
    this.verifyMyAccount();
    this.signOut();

    return { createEmailAddress: createEmailAddress, pswLogIn: pswLogIn };
  },

  /** CLICK SIGN IN LINK TO REGISTER AND CREATE AN ACCOUNT */
  clickSignIn() {
    const clickSignIn = $(
      '//div[@class="nav"]//div[@class="header_user_info"]/a'
    );
    clickSignIn.click();
  },
  //Register your email
  enterEmailAddress() {
    const randomEmailAddress = randomEmailGenerator.randomEmailGenerator();
    const emailAddressField = $('[id="email_create"]');
    emailAddressField.setValue(randomEmailAddress);
    return randomEmailAddress;
  },
  //To take you to the registration page
  createAccountBtn() {
    const createAccountBtn = $('[id="SubmitCreate"]');
    createAccountBtn.click();
  },

  //Filling the registration form
  titleSelection() {
    const titleMrs = $('[id="id_gender2"]');
    titleMrs.click();
  },

  enterFirstName() {
    const firstName = $('[id="customer_firstname"]');
    firstName.setValue("Random");
  },
  enterLastName() {
    const lastName = $('[id="customer_lastname"]');
    lastName.setValue("Surname");
  },
  validateEmailField(returnEmailAddress) {
    const validateEmail = $('[id="email"]');
    const attributeOfTheEmailField = validateEmail.getAttribute("value");
    expect(returnEmailAddress).to.equal(attributeOfTheEmailField);
  },

  //generate password
  randomPassowrd() {
    const randomPassword = autoGeneratedPassword.randomPasswordGenerator();
    const passwordField = $('[id="passwd"]');
    passwordField.setValue(randomPassword);
    return randomPassword;
  },
  dateOfBirthDay() {
    const days = $('[id="days"]');
    days.selectByAttribute("value", "3");
  },

  dateOfBirthMonth() {
    const days = $('[id="months"]');
    days.selectByAttribute("value", "12");
  },
  dateOfBirthYear() {
    const days = $('[id="years"]');
    days.selectByAttribute("value", "2000");
  },
  addressEntry() {
    const address = $('[id="address1"]');
    address.setValue("123 Test Address");
  },
  cityEntry() {
    const address = $('[id="city"]');
    address.setValue("London");
  },
  selectState() {
    const selectState = $('[id="id_state"]');
    selectState.selectByAttribute("value", "9");
  },
  enterPostcode() {
    const postCode = $('[id="postcode"]');
    const randomPostcode = randomPostcodeGenerator.randomPostcodeGenerator();
    postCode.setValue(randomPostcode);
  },
  enterMobile() {
    const phoneNumber = $('[id="phone_mobile"]');
    const randomPhoneNr = randomMobileNumber.randomMobileNumber();
    phoneNumber.setValue(randomPhoneNr);
  },
  submitRegistrationForm() {
    const regButton = $('[id="submitAccount"]');
    regButton.click();
  },

  signOut() {
    const signOut = $(
      '//div[@class="header_user_info"]/a[@class="logout"]'
    ).click();
  },
  verifyMyAccount() {
    const signOut = $(
      '//div[@class="header_user_info"]/a[@class="logout"]'
    ).getText();
    expect(signOut).to.equal("Sign out");
  },

  /* Log back in using the same details */

  // logIn(existingEmail) {
  //   const logInEmail = existingEmail;
  //   const emailField = $('[id="email"]');
  //   emailField.setValue(logInEmail);
  // },
  //
  // logInPassword(existingPsw) {
  //   const loginPassword = existingPsw;
  //   const passwordField = $('[id="passwd"]');
  //   passwordField.setValue(loginPassword);
  // },
  // logInButton() {
  //   const logInBtn = $('[id="SubmitLogin"]');
  //   logInBtn.click();
  // },
};
