const randomEmailGenerator = require("./randomEmailGenerator");
const autoGeneratedPassword = require("./autoGeneratedPasswords");

module.exports = {
  createAnAccount() {
    this.clickSignIn();
    const createEmailAddress = this.enterEmailAddress();
    this.createAccountBtn();
    this.titleSelection();
    this.enterFirstName();
    this.enterLastName();
    this.validateEmailField(createEmailAddress);
    this.randomPassowrd();
  },
  /** CLICK SIGN IN LINK TO REGISTER AND CREATE AN ACCOUNT */
  clickSignIn() {
    const clickSignIn = $(
      '//div[@class="nav"]//div[@class="header_user_info"]/a'
    );
    clickSignIn.click();
  },
  //Register your email
  enterEmailAddress() {
    const randomEmailAddress = randomEmailGenerator.randomEmailGenerator();
    const emailAddressField = $('[id="email_create"]');
    emailAddressField.setValue(randomEmailAddress);
    return randomEmailAddress;
  },
  //To take you to the registration page
  createAccountBtn() {
    const createAccountBtn = $('[id="SubmitCreate"]');
    createAccountBtn.click();
  },

  //Filling the registration form
  titleSelection() {
    const titleMrs = $('[id="id_gender2"]');
    titleMrs.click();
  },

  enterFirstName() {
    const firstName = $('[id="customer_firstname"]');
    firstName.setValue("Random");
  },
  enterLastName() {
    const lastName = $('[id="customer_lastname"]');
    lastName.setValue("Surname");
  },
  validateEmailField(returnEmailAddres) {
    const validateEmail = $('[id="email"]');
    const attributeOfTheEmailField = validateEmail.getAttribute("value");
    expect(returnEmailAddres).to.equal(attributeOfTheEmailField);
  },
  //generate password
  randomPassowrd() {
    const randomPassword = autoGeneratedPassword.randomPasswordGenerator();
    const passwordField = $('[id="passwd"]');
    passwordField.setValue(randomPassword);
    browser.pause(2000);
  },
};
